name: Norminette 42

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'meson.build'
      - 'Makefile'
      - 'README.md'
      - 'shell.nix'
      - '.envrc'
      - 'flake.nix'
      - 'flake.lock'

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
      - name: Clone by the runner
        uses: actions/checkout@v4
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python3 -m pip install -U norminette
      - name: Norminette "libft"
        run: |
          set -o pipefail
          (norminette src/ includes/ || true) | grep -E ".+\.[ch]: Error\!|^Error:" && exit 1 || exit 0